let blink = 100
let time = 2000

function randomdots () {
    while (time > 0) {
        time += -500
        led.plotBrightness(0, 0, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(1, 0, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(2, 0, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(3, 0, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(4, 0, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(0, 1, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(1, 1, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(2, 1, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(3, 1, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(4, 1, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(0, 2, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(1, 2, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(2, 2, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(3, 2, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(4, 2, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(0, 3, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(1, 3, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(2, 3, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(3, 3, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(4, 3, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(0, 4, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(1, 4, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(2, 4, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(3, 4, Math.randomRange(0, 225))
        basic.pause(blink)
        led.plotBrightness(4, 4, Math.randomRange(0, 225))
        basic.pause(blink)
    }
    basic.clearScreen()
}
