// turn three LEDs on and off in sequence
led.enable(true)
pins.digitalWritePin(DigitalPin.P12, 0)
pins.digitalWritePin(DigitalPin.P8, 0)
pins.digitalWritePin(DigitalPin.P16, 0)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P12, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P8, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P16, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P16, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P8, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P12, 0)
    basic.pause(500)
    led.plot(2, 2)
    basic.pause(500)
    led.unplot(2, 2)
})
